/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated/schedule'
import { Route as AuthenticatedGradesRouteImport } from './routes/_authenticated/grades'
import { Route as AuthenticatedFocusRouteImport } from './routes/_authenticated/focus'
import { Route as AuthenticatedClassScheduleRouteImport } from './routes/_authenticated/class-schedule'
import { Route as AuthenticatedAssignmentsRouteImport } from './routes/_authenticated/assignments'
import { Route as AuthenticatedAnnouncementsRouteImport } from './routes/_authenticated/announcements'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/_authenticated/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGradesRoute = AuthenticatedGradesRouteImport.update({
  id: '/_authenticated/grades',
  path: '/grades',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFocusRoute = AuthenticatedFocusRouteImport.update({
  id: '/_authenticated/focus',
  path: '/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClassScheduleRoute =
  AuthenticatedClassScheduleRouteImport.update({
    id: '/_authenticated/class-schedule',
    path: '/class-schedule',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAssignmentsRoute =
  AuthenticatedAssignmentsRouteImport.update({
    id: '/_authenticated/assignments',
    path: '/assignments',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAnnouncementsRoute =
  AuthenticatedAnnouncementsRouteImport.update({
    id: '/_authenticated/announcements',
    path: '/announcements',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/assignments': typeof AuthenticatedAssignmentsRoute
  '/class-schedule': typeof AuthenticatedClassScheduleRoute
  '/focus': typeof AuthenticatedFocusRoute
  '/grades': typeof AuthenticatedGradesRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/assignments': typeof AuthenticatedAssignmentsRoute
  '/class-schedule': typeof AuthenticatedClassScheduleRoute
  '/focus': typeof AuthenticatedFocusRoute
  '/grades': typeof AuthenticatedGradesRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/announcements': typeof AuthenticatedAnnouncementsRoute
  '/_authenticated/assignments': typeof AuthenticatedAssignmentsRoute
  '/_authenticated/class-schedule': typeof AuthenticatedClassScheduleRoute
  '/_authenticated/focus': typeof AuthenticatedFocusRoute
  '/_authenticated/grades': typeof AuthenticatedGradesRoute
  '/_authenticated/schedule': typeof AuthenticatedScheduleRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/announcements'
    | '/assignments'
    | '/class-schedule'
    | '/focus'
    | '/grades'
    | '/schedule'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/announcements'
    | '/assignments'
    | '/class-schedule'
    | '/focus'
    | '/grades'
    | '/schedule'
    | '/'
  id:
    | '__root__'
    | '/_authenticated/announcements'
    | '/_authenticated/assignments'
    | '/_authenticated/class-schedule'
    | '/_authenticated/focus'
    | '/_authenticated/grades'
    | '/_authenticated/schedule'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedAnnouncementsRoute: typeof AuthenticatedAnnouncementsRoute
  AuthenticatedAssignmentsRoute: typeof AuthenticatedAssignmentsRoute
  AuthenticatedClassScheduleRoute: typeof AuthenticatedClassScheduleRoute
  AuthenticatedFocusRoute: typeof AuthenticatedFocusRoute
  AuthenticatedGradesRoute: typeof AuthenticatedGradesRoute
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/grades': {
      id: '/_authenticated/grades'
      path: '/grades'
      fullPath: '/grades'
      preLoaderRoute: typeof AuthenticatedGradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/focus': {
      id: '/_authenticated/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof AuthenticatedFocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/class-schedule': {
      id: '/_authenticated/class-schedule'
      path: '/class-schedule'
      fullPath: '/class-schedule'
      preLoaderRoute: typeof AuthenticatedClassScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/assignments': {
      id: '/_authenticated/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AuthenticatedAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/announcements': {
      id: '/_authenticated/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AuthenticatedAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedAnnouncementsRoute: AuthenticatedAnnouncementsRoute,
  AuthenticatedAssignmentsRoute: AuthenticatedAssignmentsRoute,
  AuthenticatedClassScheduleRoute: AuthenticatedClassScheduleRoute,
  AuthenticatedFocusRoute: AuthenticatedFocusRoute,
  AuthenticatedGradesRoute: AuthenticatedGradesRoute,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
